package thaumcraft.common.config;
import net.minecraft.world.entity.monster.Slime;
import net.minecraft.world.entity.monster.spider.Spider;
import net.minecraft.world.entity.animal.parrot.Parrot;
import net.minecraft.world.entity.ambient.Bat;
import net.minecraft.world.entity.monster.EnderMan;
import net.minecraft.world.entity.monster.Ghast;
import java.util.HashSet;
import java.util.Iterator;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.nbt.Tag;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.world.effect.MobEffectUtil;
// removed: import net.minecraftforge.common.ForgeModContainer;
import net.neoforged.neoforge.common.NeoForge;
import net.minecraft.world.level.material.Fluid;
import net.neoforged.neoforge.fluids.FluidStack;
import net.neoforged.neoforge.fluids.FluidUtil;
import net.neoforged.bus.api.Event;
import thaumcraft.api.ThaumcraftApi;
import thaumcraft.api.aspects.Aspect;
import thaumcraft.api.aspects.AspectEventProxy;
import thaumcraft.api.aspects.AspectList;
import thaumcraft.api.aspects.AspectRegistryEvent;
import thaumcraft.api.blocks.BlocksTC;
import thaumcraft.api.internal.CommonInternals;
import thaumcraft.api.items.ItemsTC;
import thaumcraft.common.lib.crafting.ThaumcraftCraftingManager;
import net.minecraft.world.entity.monster.zombie.Zombie;


public class ConfigAspects
{
    public static String[] dyes;

    private static ItemStack s(net.minecraft.world.level.ItemLike item) {
        return (item != null) ? new ItemStack(item) : ItemStack.EMPTY;
    }
    
    public static void postInit() {
        CommonInternals.objectTags.clear();
        registerItemAspects();
        registerEntityAspects();
        AspectRegistryEvent are = new AspectRegistryEvent();
        are.register = new AspectEventProxy();
        NeoForge.EVENT_BUS.post(are);
    }
    
    private static void registerEntityAspects() {
        ThaumcraftApi.registerEntityTag("Zombie", new AspectList().add(Aspect.UNDEAD, 20).add(Aspect.MAN, 10).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerEntityTag("Husk", new AspectList().add(Aspect.UNDEAD, 20).add(Aspect.MAN, 10).add(Aspect.FIRE, 5));
        ThaumcraftApi.registerEntityTag("Giant", new AspectList().add(Aspect.UNDEAD, 25).add(Aspect.MAN, 15).add(Aspect.EARTH, 10));
        ThaumcraftApi.registerEntityTag("Skeleton", new AspectList().add(Aspect.UNDEAD, 20).add(Aspect.MAN, 5).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerEntityTag("WitherSkeleton", new AspectList().add(Aspect.UNDEAD, 25).add(Aspect.MAN, 5).add(Aspect.ENTROPY, 10));
        ThaumcraftApi.registerEntityTag("Creeper", new AspectList().add(Aspect.PLANT, 15).add(Aspect.FIRE, 15));
        ThaumcraftApi.registerEntityTag("Creeper", new AspectList().add(Aspect.PLANT, 15).add(Aspect.FIRE, 15).add(Aspect.ENERGY, 15), new ThaumcraftApi.EntityTagsNBT("powered", 1));
        ThaumcraftApi.registerEntityTag("Horse", new AspectList().add(Aspect.BEAST, 15).add(Aspect.EARTH, 5).add(Aspect.AIR, 5));
        ThaumcraftApi.registerEntityTag("Donkey", new AspectList().add(Aspect.BEAST, 15).add(Aspect.EARTH, 5).add(Aspect.AIR, 5));
        ThaumcraftApi.registerEntityTag("Mule", new AspectList().add(Aspect.BEAST, 15).add(Aspect.EARTH, 5).add(Aspect.AIR, 5));
        ThaumcraftApi.registerEntityTag("SkeletonHorse", new AspectList().add(Aspect.BEAST, 5).add(Aspect.UNDEAD, 10).add(Aspect.EARTH, 5).add(Aspect.AIR, 5));
        ThaumcraftApi.registerEntityTag("ZombieHorse", new AspectList().add(Aspect.BEAST, 10).add(Aspect.UNDEAD, 5).add(Aspect.EARTH, 5).add(Aspect.AIR, 5));
        ThaumcraftApi.registerEntityTag("Pig", new AspectList().add(Aspect.BEAST, 10).add(Aspect.EARTH, 10).add(Aspect.DESIRE, 5));
        ThaumcraftApi.registerEntityTag("XPOrb", new AspectList().add(Aspect.MIND, 10));
        ThaumcraftApi.registerEntityTag("Sheep", new AspectList().add(Aspect.BEAST, 10).add(Aspect.EARTH, 10));
        ThaumcraftApi.registerEntityTag("Cow", new AspectList().add(Aspect.BEAST, 15).add(Aspect.EARTH, 15));
        ThaumcraftApi.registerEntityTag("MushroomCow", new AspectList().add(Aspect.BEAST, 15).add(Aspect.PLANT, 15).add(Aspect.EARTH, 15));
        ThaumcraftApi.registerEntityTag("SnowMan", new AspectList().add(Aspect.COLD, 10).add(Aspect.MAN, 5).add(Aspect.MECHANISM, 5).add(Aspect.MAGIC, 5));
        ThaumcraftApi.registerEntityTag("Ozelot", new AspectList().add(Aspect.BEAST, 10).add(Aspect.ENTROPY, 10));
        ThaumcraftApi.registerEntityTag("Chicken", new AspectList().add(Aspect.BEAST, 5).add(Aspect.FLIGHT, 5).add(Aspect.AIR, 5));
        ThaumcraftApi.registerEntityTag("Squid", new AspectList().add(Aspect.BEAST, 5).add(Aspect.WATER, 10));
        ThaumcraftApi.registerEntityTag("Wolf", new AspectList().add(Aspect.BEAST, 15).add(Aspect.EARTH, 10).add(Aspect.AVERSION, 5));
        ThaumcraftApi.registerEntityTag("Bat", new AspectList().add(Aspect.BEAST, 5).add(Aspect.FLIGHT, 5).add(Aspect.DARKNESS, 5));
        ThaumcraftApi.registerEntityTag("Spider", new AspectList().add(Aspect.BEAST, 10).add(Aspect.ENTROPY, 10).add(Aspect.TRAP, 10));
        ThaumcraftApi.registerEntityTag("Slime", new AspectList().add(Aspect.LIFE, 10).add(Aspect.WATER, 10).add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerEntityTag("Ghast", new AspectList().add(Aspect.UNDEAD, 15).add(Aspect.FIRE, 15));
        ThaumcraftApi.registerEntityTag("PigZombie", new AspectList().add(Aspect.UNDEAD, 15).add(Aspect.FIRE, 15).add(Aspect.BEAST, 10));
        ThaumcraftApi.registerEntityTag("EnderMan", new AspectList().add(Aspect.ELDRITCH, 10).add(Aspect.MOTION, 15).add(Aspect.DESIRE, 5));
        ThaumcraftApi.registerEntityTag("CaveSpider", new AspectList().add(Aspect.BEAST, 5).add(Aspect.DEATH, 10).add(Aspect.TRAP, 10));
        ThaumcraftApi.registerEntityTag("Silverfish", new AspectList().add(Aspect.BEAST, 5).add(Aspect.EARTH, 10));
        ThaumcraftApi.registerEntityTag("Blaze", new AspectList().add(Aspect.ELDRITCH, 5).add(Aspect.FIRE, 15).add(Aspect.FLIGHT, 5));
        ThaumcraftApi.registerEntityTag("LavaSlime", new AspectList().add(Aspect.WATER, 5).add(Aspect.FIRE, 10).add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerEntityTag("EnderDragon", new AspectList().add(Aspect.ELDRITCH, 50).add(Aspect.BEAST, 30).add(Aspect.ENTROPY, 50).add(Aspect.FLIGHT, 10));
        ThaumcraftApi.registerEntityTag("WitherBoss", new AspectList().add(Aspect.UNDEAD, 50).add(Aspect.ENTROPY, 25).add(Aspect.FIRE, 25));
        ThaumcraftApi.registerEntityTag("Witch", new AspectList().add(Aspect.MAN, 15).add(Aspect.MAGIC, 5).add(Aspect.ALCHEMY, 10));
        ThaumcraftApi.registerEntityTag("Villager", new AspectList().add(Aspect.MAN, 15));
        ThaumcraftApi.registerEntityTag("VillagerGolem", new AspectList().add(Aspect.METAL, 15).add(Aspect.MAN, 5).add(Aspect.MECHANISM, 5).add(Aspect.MAGIC, 5));
        ThaumcraftApi.registerEntityTag("EnderCrystal", new AspectList().add(Aspect.ELDRITCH, 15).add(Aspect.AURA, 15).add(Aspect.LIFE, 15));
        ThaumcraftApi.registerEntityTag("ItemFrame", new AspectList().add(Aspect.SENSES, 5).add(Aspect.CRAFT, 5));
        ThaumcraftApi.registerEntityTag("Painting", new AspectList().add(Aspect.SENSES, 10).add(Aspect.CRAFT, 5));
        ThaumcraftApi.registerEntityTag("Guardian", new AspectList().add(Aspect.BEAST, 10).add(Aspect.ELDRITCH, 10).add(Aspect.WATER, 10));
        ThaumcraftApi.registerEntityTag("Guardian", new AspectList().add(Aspect.BEAST, 10).add(Aspect.ELDRITCH, 15).add(Aspect.WATER, 15), new ThaumcraftApi.EntityTagsNBT("Elder", true));
        ThaumcraftApi.registerEntityTag("Rabbit", new AspectList().add(Aspect.BEAST, 5).add(Aspect.EARTH, 5).add(Aspect.MOTION, 5));
        ThaumcraftApi.registerEntityTag("Endermite", new AspectList().add(Aspect.BEAST, 5).add(Aspect.ELDRITCH, 5).add(Aspect.MOTION, 5));
        ThaumcraftApi.registerEntityTag("PolarBear", new AspectList().add(Aspect.BEAST, 15).add(Aspect.COLD, 10));
        ThaumcraftApi.registerEntityTag("Shulker", new AspectList().add(Aspect.ELDRITCH, 10).add(Aspect.TRAP, 5).add(Aspect.FLIGHT, 5).add(Aspect.PROTECT, 5));
        ThaumcraftApi.registerEntityTag("EvocationIllager", new AspectList().add(Aspect.ELDRITCH, 5).add(Aspect.MAGIC, 5).add(Aspect.MAN, 10));
        ThaumcraftApi.registerEntityTag("VindicationIllager", new AspectList().add(Aspect.AVERSION, 5).add(Aspect.MAGIC, 5).add(Aspect.MAN, 10));
        ThaumcraftApi.registerEntityTag("IllusionIllager", new AspectList().add(Aspect.SENSES, 5).add(Aspect.MAGIC, 5).add(Aspect.MAN, 10));
        ThaumcraftApi.registerEntityTag("Llama", new AspectList().add(Aspect.BEAST, 15).add(Aspect.WATER, 5));
        ThaumcraftApi.registerEntityTag("Parrot", new AspectList().add(Aspect.BEAST, 5).add(Aspect.FLIGHT, 5).add(Aspect.SENSES, 5));
        ThaumcraftApi.registerEntityTag("Stray", new AspectList().add(Aspect.UNDEAD, 20).add(Aspect.MAN, 5).add(Aspect.TRAP, 5));
        ThaumcraftApi.registerEntityTag("Vex", new AspectList().add(Aspect.ELDRITCH, 5).add(Aspect.FLIGHT, 5).add(Aspect.MAGIC, 5).add(Aspect.MAN, 5));
        ThaumcraftApi.registerEntityTag("Stray", new AspectList().add(Aspect.UNDEAD, 20).add(Aspect.MAN, 5).add(Aspect.TRAP, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.FluxRift", new AspectList().add(Aspect.FLUX, 20).add(Aspect.ELDRITCH, 20).add(Aspect.AURA, 20));
        ThaumcraftApi.registerEntityTag("Thaumcraft.Firebat", new AspectList().add(Aspect.BEAST, 5).add(Aspect.FLIGHT, 5).add(Aspect.FIRE, 10));
        ThaumcraftApi.registerEntityTag("Thaumcraft.Pech", new AspectList().add(Aspect.MAN, 10).add(Aspect.AURA, 5).add(Aspect.EXCHANGE, 10).add(Aspect.DESIRE, 5), new ThaumcraftApi.EntityTagsNBT("PechType", 0));
        ThaumcraftApi.registerEntityTag("Thaumcraft.Pech", new AspectList().add(Aspect.MAN, 10).add(Aspect.AURA, 5).add(Aspect.EXCHANGE, 10).add(Aspect.AVERSION, 5), new ThaumcraftApi.EntityTagsNBT("PechType", 1));
        ThaumcraftApi.registerEntityTag("Thaumcraft.Pech", new AspectList().add(Aspect.MAN, 10).add(Aspect.AURA, 5).add(Aspect.EXCHANGE, 10).add(Aspect.MAGIC, 5), new ThaumcraftApi.EntityTagsNBT("PechType", 2));
        ThaumcraftApi.registerEntityTag("Thaumcraft.ThaumSlime", new AspectList().add(Aspect.LIFE, 5).add(Aspect.WATER, 5).add(Aspect.FLUX, 5).add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.BrainyZombie", new AspectList().add(Aspect.UNDEAD, 20).add(Aspect.MAN, 10).add(Aspect.MIND, 5).add(Aspect.AVERSION, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.GiantBrainyZombie", new AspectList().add(Aspect.UNDEAD, 25).add(Aspect.MAN, 15).add(Aspect.MIND, 5).add(Aspect.AVERSION, 10));
        ThaumcraftApi.registerEntityTag("Thaumcraft.Taintacle", new AspectList().add(Aspect.FLUX, 15).add(Aspect.BEAST, 10));
        ThaumcraftApi.registerEntityTag("Thaumcraft.TaintSeed", new AspectList().add(Aspect.FLUX, 20).add(Aspect.AURA, 10).add(Aspect.PLANT, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.TaintSeedPrime", new AspectList().add(Aspect.FLUX, 25).add(Aspect.AURA, 15).add(Aspect.PLANT, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.TaintacleTiny", new AspectList().add(Aspect.FLUX, 5).add(Aspect.BEAST, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.TaintSwarm", new AspectList().add(Aspect.FLUX, 15).add(Aspect.AIR, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.MindSpider", new AspectList().add(Aspect.FLUX, 5).add(Aspect.FIRE, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.EldritchGuardian", new AspectList().add(Aspect.ELDRITCH, 20).add(Aspect.DEATH, 20).add(Aspect.UNDEAD, 20));
        ThaumcraftApi.registerEntityTag("Thaumcraft.CultistKnight", new AspectList().add(Aspect.ELDRITCH, 5).add(Aspect.MAN, 15).add(Aspect.AVERSION, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.CultistCleric", new AspectList().add(Aspect.ELDRITCH, 5).add(Aspect.MAN, 15).add(Aspect.AVERSION, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.EldritchCrab", new AspectList().add(Aspect.ELDRITCH, 10).add(Aspect.BEAST, 10).add(Aspect.TRAP, 10));
        ThaumcraftApi.registerEntityTag("Thaumcraft.InhabitedZombie", new AspectList().add(Aspect.ELDRITCH, 10).add(Aspect.UNDEAD, 10).add(Aspect.MAN, 5));
        ThaumcraftApi.registerEntityTag("Thaumcraft.TaintSeed", new AspectList().add(Aspect.PLANT, 20).add(Aspect.BEAST, 20).add(Aspect.FLUX, 20));
        ThaumcraftApi.registerEntityTag("Thaumcraft.TaintSeedPrime", new AspectList().add(Aspect.PLANT, 30).add(Aspect.BEAST, 30).add(Aspect.FLUX, 30));
        ThaumcraftApi.registerEntityTag("Thaumcraft.EldritchWarden", new AspectList().add(Aspect.ELDRITCH, 40).add(Aspect.DEATH, 40).add(Aspect.UNDEAD, 40));
        ThaumcraftApi.registerEntityTag("Thaumcraft.EldritchGolem", new AspectList().add(Aspect.ELDRITCH, 40).add(Aspect.ENERGY, 40).add(Aspect.MECHANISM, 40));
        ThaumcraftApi.registerEntityTag("Thaumcraft.CultistLeader", new AspectList().add(Aspect.ELDRITCH, 40).add(Aspect.AVERSION, 40).add(Aspect.MAN, 40));
        ThaumcraftApi.registerEntityTag("Thaumcraft.TaintacleGiant", new AspectList().add(Aspect.ELDRITCH, 40).add(Aspect.BEAST, 40).add(Aspect.FLUX, 40));
        for (Aspect tag : Aspect.aspects.values()) {
            ThaumcraftApi.registerEntityTag("Thaumcraft.Wisp", new AspectList().add(tag, 5).add(Aspect.AURA, 5).add(Aspect.FLIGHT, 5), new ThaumcraftApi.EntityTagsNBT("Type", tag.getTag()));
        }
        ThaumcraftApi.registerEntityTag("Thaumcraft.Golem", new AspectList().add(Aspect.MECHANISM, 10).add(Aspect.MAN, 10).add(Aspect.MOTION, 10));
    }
    
    private static void registerItemAspects() {
        ThaumcraftApi.registerObjectTag("oreLapis", new AspectList().add(Aspect.EARTH, 5).add(Aspect.SENSES, 15));
        ThaumcraftApi.registerObjectTag("oreDiamond", new AspectList().add(Aspect.EARTH, 5).add(Aspect.DESIRE, 15).add(Aspect.CRYSTAL, 15));
        ThaumcraftApi.registerObjectTag("gemDiamond", new AspectList().add(Aspect.CRYSTAL, 15).add(Aspect.DESIRE, 15));
        ThaumcraftApi.registerObjectTag("oreRedstone", new AspectList().add(Aspect.EARTH, 5).add(Aspect.ENERGY, 15));
        ThaumcraftApi.registerObjectTag(s(Blocks.REDSTONE_ORE), new AspectList().add(Aspect.EARTH, 5).add(Aspect.ENERGY, 15));
        ThaumcraftApi.registerObjectTag("oreEmerald", new AspectList().add(Aspect.EARTH, 5).add(Aspect.DESIRE, 10).add(Aspect.CRYSTAL, 15));
        ThaumcraftApi.registerObjectTag("gemEmerald", new AspectList().add(Aspect.CRYSTAL, 15).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag("oreQuartz", new AspectList().add(Aspect.EARTH, 5).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag("gemQuartz", new AspectList().add(Aspect.CRYSTAL, 5));
        ThaumcraftApi.registerObjectTag("oreIron", new AspectList().add(Aspect.EARTH, 5).add(Aspect.METAL, 15));
        ThaumcraftApi.registerObjectTag("dustIron", new AspectList().add(Aspect.METAL, 15).add(Aspect.ENTROPY, 1));
        ThaumcraftApi.registerObjectTag("ingotIron", new AspectList().add(Aspect.METAL, 15));
        ThaumcraftApi.registerObjectTag("oreGold", new AspectList().add(Aspect.EARTH, 5).add(Aspect.METAL, 10).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag("dustGold", new AspectList().add(Aspect.METAL, 10).add(Aspect.DESIRE, 10).add(Aspect.ENTROPY, 1));
        ThaumcraftApi.registerObjectTag("ingotGold", new AspectList().add(Aspect.METAL, 10).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(s(Blocks.COAL_ORE), new AspectList().add(Aspect.EARTH, 5).add(Aspect.ENERGY, 15).add(Aspect.FIRE, 15));
        ThaumcraftApi.registerObjectTag(s(Items.COAL), new AspectList().add(Aspect.ENERGY, 10).add(Aspect.FIRE, 10));
        ThaumcraftApi.registerObjectTag("dustRedstone", new AspectList().add(Aspect.ENERGY, 10));
        ThaumcraftApi.registerObjectTag("dustGlowstone", new AspectList().add(Aspect.SENSES, 5).add(Aspect.LIGHT, 10));
        ThaumcraftApi.registerObjectTag("glowstone", new AspectList(s(Blocks.GLOWSTONE)));
        ThaumcraftApi.registerObjectTag("ingotCopper", new AspectList().add(Aspect.METAL, 10).add(Aspect.EXCHANGE, 5));
        ThaumcraftApi.registerObjectTag("dustCopper", new AspectList().add(Aspect.METAL, 10).add(Aspect.ENTROPY, 1).add(Aspect.EXCHANGE, 5));
        ThaumcraftApi.registerObjectTag("oreCopper", new AspectList().add(Aspect.METAL, 10).add(Aspect.EARTH, 5).add(Aspect.EXCHANGE, 5));
        ThaumcraftApi.registerObjectTag("clusterCopper", new AspectList().add(Aspect.ORDER, 5).add(Aspect.METAL, 15).add(Aspect.EARTH, 5).add(Aspect.EXCHANGE, 10));
        ThaumcraftApi.registerObjectTag("ingotTin", new AspectList().add(Aspect.METAL, 10).add(Aspect.CRYSTAL, 5));
        ThaumcraftApi.registerObjectTag("dustTin", new AspectList().add(Aspect.METAL, 10).add(Aspect.ENTROPY, 1).add(Aspect.CRYSTAL, 5));
        ThaumcraftApi.registerObjectTag("oreTin", new AspectList().add(Aspect.METAL, 10).add(Aspect.EARTH, 5).add(Aspect.CRYSTAL, 5));
        ThaumcraftApi.registerObjectTag("clusterTin", new AspectList().add(Aspect.ORDER, 5).add(Aspect.METAL, 15).add(Aspect.EARTH, 5).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag("ingotSilver", new AspectList().add(Aspect.METAL, 10).add(Aspect.DESIRE, 5));
        ThaumcraftApi.registerObjectTag("dustSilver", new AspectList().add(Aspect.METAL, 10).add(Aspect.ENTROPY, 1).add(Aspect.DESIRE, 5));
        ThaumcraftApi.registerObjectTag("oreSilver", new AspectList().add(Aspect.METAL, 10).add(Aspect.EARTH, 5).add(Aspect.DESIRE, 5));
        ThaumcraftApi.registerObjectTag("clusterSilver", new AspectList().add(Aspect.ORDER, 5).add(Aspect.METAL, 15).add(Aspect.EARTH, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag("ingotLead", new AspectList().add(Aspect.METAL, 10).add(Aspect.ORDER, 5));
        ThaumcraftApi.registerObjectTag("dustLead", new AspectList().add(Aspect.METAL, 10).add(Aspect.ENTROPY, 1).add(Aspect.ORDER, 5));
        ThaumcraftApi.registerObjectTag("oreLead", new AspectList().add(Aspect.METAL, 10).add(Aspect.EARTH, 5).add(Aspect.ORDER, 5));
        ThaumcraftApi.registerObjectTag("clusterLead", new AspectList().add(Aspect.ORDER, 5).add(Aspect.METAL, 15).add(Aspect.EARTH, 5).add(Aspect.ORDER, 10));
        ThaumcraftApi.registerObjectTag("ingotBrass", new AspectList().add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
        ThaumcraftApi.registerObjectTag("dustBrass", new AspectList().add(Aspect.METAL, 10).add(Aspect.ENTROPY, 1).add(Aspect.TOOL, 5));
        ThaumcraftApi.registerObjectTag("ingotBronze", new AspectList().add(Aspect.METAL, 10).add(Aspect.TOOL, 5));
        ThaumcraftApi.registerObjectTag("dustBronze", new AspectList().add(Aspect.METAL, 10).add(Aspect.ENTROPY, 1).add(Aspect.TOOL, 5));
        ThaumcraftApi.registerObjectTag("oreUranium", new AspectList().add(Aspect.METAL, 10).add(Aspect.DEATH, 5).add(Aspect.ENERGY, 10));
        ThaumcraftApi.registerObjectTag("itemDropUranium", new AspectList().add(Aspect.METAL, 10).add(Aspect.DEATH, 5).add(Aspect.ENERGY, 10));
        ThaumcraftApi.registerObjectTag("ingotUranium", new AspectList().add(Aspect.METAL, 10).add(Aspect.DEATH, 5).add(Aspect.ENERGY, 10));
        ThaumcraftApi.registerObjectTag("gemRuby", new AspectList().add(Aspect.CRYSTAL, 10).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag("gemGreenSapphire", new AspectList().add(Aspect.CRYSTAL, 10).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag("gemSapphire", new AspectList().add(Aspect.CRYSTAL, 10).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag("ingotSteel", new AspectList().add(Aspect.METAL, 15).add(Aspect.ORDER, 5));
        ThaumcraftApi.registerObjectTag("itemRubber", new AspectList().add(Aspect.MOTION, 5).add(Aspect.TOOL, 5));
        ThaumcraftApi.registerObjectTag("stone", new AspectList().add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag("stoneGranite", new AspectList().add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag("stoneDiorite", new AspectList().add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag("stoneAndesite", new AspectList().add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag("cobblestone", new AspectList().add(Aspect.EARTH, 5).add(Aspect.ENTROPY, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.BEDROCK), new AspectList().add(Aspect.VOID, 25).add(Aspect.ENTROPY, 25).add(Aspect.EARTH, 25).add(Aspect.DARKNESS, 25));
        ThaumcraftApi.registerObjectTag("dirt", new AspectList().add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag(s(Blocks.PODZOL), new AspectList().add(Aspect.EARTH, 5).add(Aspect.PLANT, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.FARMLAND), new AspectList().add(Aspect.EARTH, 5).add(Aspect.WATER, 2).add(Aspect.ORDER, 2));
        ThaumcraftApi.registerObjectTag("sand", new AspectList().add(Aspect.EARTH, 5).add(Aspect.ENTROPY, 5));
        ThaumcraftApi.registerObjectTag("grass", new AspectList().add(Aspect.EARTH, 5).add(Aspect.PLANT, 2));
        ThaumcraftApi.registerObjectTag(s(Blocks.DIRT_PATH), new AspectList().add(Aspect.EARTH, 5).add(Aspect.PLANT, 2).add(Aspect.ORDER, 2));
        ThaumcraftApi.registerObjectTag("endstone", new AspectList().add(Aspect.EARTH, 5).add(Aspect.DARKNESS, 5));
        ThaumcraftApi.registerObjectTag("gravel", new AspectList().add(Aspect.EARTH, 5).add(Aspect.ENTROPY, 2));
        ThaumcraftApi.registerObjectTag(s(Blocks.MYCELIUM), new AspectList().add(Aspect.EARTH, 5).add(Aspect.PLANT, 1).add(Aspect.FLUX, 1));
        ThaumcraftApi.registerObjectTag(s(Items.CLAY_BALL), new AspectList().add(Aspect.WATER, 5).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag(s(Blocks.TERRACOTTA), new AspectList(s(Blocks.CLAY)).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.WHITE_TERRACOTTA), new AspectList(s(Blocks.CLAY)).add(Aspect.FIRE, 1).add(Aspect.SENSES, 1));
        ThaumcraftApi.registerObjectTag(s(Items.BRICK), new AspectList(s(Items.CLAY_BALL)).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag("netherrack", new AspectList().add(Aspect.EARTH, 5).add(Aspect.FIRE, 2));
        ThaumcraftApi.registerObjectTag("ingotBrickNether", new AspectList(s(Blocks.NETHERRACK)).add(Aspect.FIRE, 1).add(Aspect.ORDER, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.SOUL_SAND), new AspectList().add(Aspect.EARTH, 3).add(Aspect.TRAP, 1).add(Aspect.SOUL, 3));
        ThaumcraftApi.registerObjectTag("blockGlass", new AspectList().add(Aspect.CRYSTAL, 5));
        ThaumcraftApi.registerObjectTag(s(Blocks.MOSSY_COBBLESTONE), new AspectList().add(Aspect.EARTH, 5).add(Aspect.PLANT, 3).add(Aspect.ENTROPY, 1));
        ThaumcraftApi.registerObjectTag("obsidian", new AspectList().add(Aspect.EARTH, 5).add(Aspect.FIRE, 5).add(Aspect.DARKNESS, 5));
        ThaumcraftApi.registerObjectTag(s(Blocks.MOSSY_STONE_BRICKS), new AspectList(s(Blocks.STONE_BRICKS)).add(Aspect.PLANT, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.CRACKED_STONE_BRICKS), new AspectList(s(Blocks.STONE_BRICKS)).add(Aspect.ENTROPY, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.CHISELED_STONE_BRICKS), new AspectList(s(Blocks.STONE_BRICKS)).add(Aspect.ORDER, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.CHISELED_SANDSTONE), new AspectList(s(Blocks.SANDSTONE)).add(Aspect.ORDER, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.SMOOTH_SANDSTONE), new AspectList(s(Blocks.SANDSTONE)).add(Aspect.ORDER, 1));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.WHITE_CONCRETE), new AspectList(s(Blocks.WHITE_CONCRETE_POWDER)).add(Aspect.WATER, 1).add(Aspect.ORDER, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.BLACK_GLAZED_TERRACOTTA), new AspectList(s(Blocks.WHITE_TERRACOTTA)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.BLUE_GLAZED_TERRACOTTA), new AspectList(s(Blocks.WHITE_TERRACOTTA)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.BROWN_GLAZED_TERRACOTTA), new AspectList(s(Blocks.WHITE_TERRACOTTA)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.CYAN_GLAZED_TERRACOTTA), new AspectList(s(Blocks.WHITE_TERRACOTTA)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.GRAY_GLAZED_TERRACOTTA), new AspectList(s(Blocks.WHITE_TERRACOTTA)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.GREEN_GLAZED_TERRACOTTA), new AspectList(s(Blocks.WHITE_TERRACOTTA)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.LIGHT_BLUE_GLAZED_TERRACOTTA), new AspectList(s(Blocks.WHITE_TERRACOTTA)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.LIME_GLAZED_TERRACOTTA), new AspectList(s(Blocks.WHITE_TERRACOTTA)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.MAGENTA_GLAZED_TERRACOTTA), new AspectList(s(Blocks.WHITE_TERRACOTTA)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.ORANGE_GLAZED_TERRACOTTA), new AspectList(s(Blocks.WHITE_TERRACOTTA)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.PINK_GLAZED_TERRACOTTA), new AspectList(s(Blocks.WHITE_TERRACOTTA)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.PURPLE_GLAZED_TERRACOTTA), new AspectList(s(Blocks.WHITE_TERRACOTTA)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.RED_GLAZED_TERRACOTTA), new AspectList(s(Blocks.WHITE_TERRACOTTA)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.LIGHT_GRAY_GLAZED_TERRACOTTA), new AspectList(s(Blocks.WHITE_TERRACOTTA)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.WHITE_GLAZED_TERRACOTTA), new AspectList(s(Blocks.WHITE_TERRACOTTA)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.YELLOW_GLAZED_TERRACOTTA), new AspectList(s(Blocks.WHITE_TERRACOTTA)).add(Aspect.SENSES, 1).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag("logWood", new AspectList().add(Aspect.PLANT, 20));
        ThaumcraftApi.registerObjectTag("treeSapling", new AspectList().add(Aspect.PLANT, 15).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag("treeLeaves", new AspectList().add(Aspect.PLANT, 5));
        ThaumcraftApi.registerObjectTag(s(Blocks.SHORT_GRASS), new AspectList().add(Aspect.PLANT, 5).add(Aspect.AIR, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.SUNFLOWER), new AspectList().add(Aspect.PLANT, 5).add(Aspect.AIR, 1).add(Aspect.SENSES, 5).add(Aspect.LIFE, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.LILAC), new AspectList().add(Aspect.PLANT, 5).add(Aspect.AIR, 1).add(Aspect.SENSES, 5).add(Aspect.LIFE, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.TALL_GRASS), new AspectList().add(Aspect.PLANT, 5).add(Aspect.AIR, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.LARGE_FERN), new AspectList().add(Aspect.PLANT, 5).add(Aspect.AIR, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.ROSE_BUSH), new AspectList().add(Aspect.PLANT, 5).add(Aspect.AIR, 1).add(Aspect.SENSES, 5).add(Aspect.LIFE, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.PEONY), new AspectList().add(Aspect.PLANT, 5).add(Aspect.AIR, 1).add(Aspect.SENSES, 5).add(Aspect.LIFE, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.LILY_PAD), new AspectList().add(Aspect.PLANT, 5).add(Aspect.WATER, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.DEAD_BUSH), new AspectList().add(Aspect.PLANT, 5).add(Aspect.ENTROPY, 1));
        ThaumcraftApi.registerObjectTag("vine", new AspectList().add(Aspect.PLANT, 5));
        ThaumcraftApi.registerObjectTag(s(Items.WHEAT_SEEDS), new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 1));
        ThaumcraftApi.registerObjectTag(s(Items.MELON_SEEDS), new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 1));
        ThaumcraftApi.registerObjectTag(s(Items.PUMPKIN_SEEDS), new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 1));
        ThaumcraftApi.registerObjectTag(s(Items.BEETROOT_SEEDS), new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 1));
        ThaumcraftApi.registerObjectTag("cropNetherWart", new AspectList().add(Aspect.PLANT, 1).add(Aspect.FLUX, 2).add(Aspect.ALCHEMY, 3));
        ThaumcraftApi.registerObjectTag(s(Blocks.POPPY), new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 1).add(Aspect.SENSES, 5));
        ThaumcraftApi.registerObjectTag(s(Blocks.DANDELION), new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 1).add(Aspect.SENSES, 5));
        ThaumcraftApi.registerObjectTag("blockCactus", new AspectList().add(Aspect.PLANT, 5).add(Aspect.WATER, 5).add(Aspect.AVERSION, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.BROWN_MUSHROOM), new AspectList().add(Aspect.PLANT, 5).add(Aspect.DARKNESS, 2).add(Aspect.EARTH, 2));
        ThaumcraftApi.registerObjectTag(s(Blocks.RED_MUSHROOM), new AspectList().add(Aspect.PLANT, 5).add(Aspect.DARKNESS, 2).add(Aspect.FIRE, 2));
        ThaumcraftApi.registerObjectTag(s(Blocks.BROWN_MUSHROOM_BLOCK), new AspectList().add(Aspect.PLANT, 5).add(Aspect.DARKNESS, 2).add(Aspect.EARTH, 2));
        ThaumcraftApi.registerObjectTag(s(Blocks.RED_MUSHROOM_BLOCK), new AspectList().add(Aspect.PLANT, 5).add(Aspect.DARKNESS, 2).add(Aspect.FIRE, 2));
        ThaumcraftApi.registerObjectTag("sugarcane", new AspectList().add(Aspect.PLANT, 5).add(Aspect.WATER, 3).add(Aspect.AIR, 2));
        ThaumcraftApi.registerObjectTag("cropWheat", new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(s(Items.APPLE), new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag("cropCarrot", new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 5).add(Aspect.SENSES, 5));
        ThaumcraftApi.registerObjectTag("cropPotato", new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 5).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag(s(Items.BEETROOT), new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 5).add(Aspect.DESIRE, 1));
        ThaumcraftApi.registerObjectTag(s(Items.BAKED_POTATO), new AspectList().add(Aspect.PLANT, 5).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(s(Items.POISONOUS_POTATO), new AspectList().add(Aspect.PLANT, 5).add(Aspect.DEATH, 5));
        ThaumcraftApi.registerObjectTag(s(Blocks.PUMPKIN), new AspectList().add(Aspect.PLANT, 10));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.MELON), new AspectList().add(Aspect.PLANT, 10).remove(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(s(Items.MELON), new AspectList().add(Aspect.PLANT, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.SPONGE), new AspectList().add(Aspect.EARTH, 5).add(Aspect.TRAP, 5).add(Aspect.VOID, 5));
        ThaumcraftApi.registerObjectTag(s(Blocks.WET_SPONGE), new AspectList().add(Aspect.EARTH, 5).add(Aspect.TRAP, 5).add(Aspect.WATER, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.SUGAR), new AspectList().add(Aspect.DESIRE, 1).add(Aspect.ENERGY, 1));
        ThaumcraftApi.registerComplexObjectTag(s(Items.CAKE), new AspectList().add(Aspect.DESIRE, 1).add(Aspect.LIFE, 2));
        ThaumcraftApi.registerComplexObjectTag(s(Items.PUMPKIN_PIE), new AspectList().add(Aspect.DESIRE, 1).add(Aspect.LIFE, 2));
        ThaumcraftApi.registerObjectTag(s(Blocks.WHITE_WOOL), new AspectList().add(Aspect.BEAST, 15).add(Aspect.CRAFT, 5));
        ThaumcraftApi.registerObjectTag(s(Items.EXPERIENCE_BOTTLE), new AspectList().add(Aspect.MIND, 20));
        ThaumcraftApi.registerObjectTag(s(Items.NAME_TAG), new AspectList().add(Aspect.MIND, 10).add(Aspect.BEAST, 10));
        ThaumcraftApi.registerObjectTag(s(Items.IRON_HORSE_ARMOR), new AspectList().add(Aspect.METAL, 15).add(Aspect.PROTECT, 10).add(Aspect.BEAST, 5));
        ThaumcraftApi.registerObjectTag(s(Items.GOLDEN_HORSE_ARMOR), new AspectList().add(Aspect.METAL, 10).add(Aspect.PROTECT, 15).add(Aspect.BEAST, 5));
        ThaumcraftApi.registerObjectTag(s(Items.DIAMOND_HORSE_ARMOR), new AspectList().add(Aspect.CRYSTAL, 15).add(Aspect.PROTECT, 20).add(Aspect.BEAST, 5));
        ThaumcraftApi.registerObjectTag(s(Blocks.FIRE), new AspectList().add(Aspect.FIRE, 20));
        ThaumcraftApi.registerObjectTag(s(Blocks.MAGMA_BLOCK), new AspectList().add(Aspect.FIRE, 10).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag(s(Blocks.CHORUS_FLOWER), new AspectList().add(Aspect.ELDRITCH, 5).add(Aspect.SENSES, 5).add(Aspect.PLANT, 5));
        ThaumcraftApi.registerObjectTag(s(Blocks.CHORUS_PLANT), new AspectList().add(Aspect.ELDRITCH, 5).add(Aspect.PLANT, 5));
        ThaumcraftApi.registerObjectTag(s(Items.CHORUS_FRUIT), new AspectList().add(Aspect.ELDRITCH, 5).add(Aspect.SENSES, 5).add(Aspect.PLANT, 5));
        ThaumcraftApi.registerObjectTag(s(Items.POPPED_CHORUS_FRUIT), new AspectList().add(Aspect.ELDRITCH, 5).add(Aspect.SENSES, 5).add(Aspect.PLANT, 4).add(Aspect.FIRE, 1));
        ThaumcraftApi.registerObjectTag(s(Blocks.ICE), new AspectList().add(Aspect.COLD, 20));
        ThaumcraftApi.registerObjectTag(s(Blocks.PACKED_ICE), new AspectList().add(Aspect.COLD, 15).add(Aspect.ORDER, 5));
        ThaumcraftApi.registerObjectTag(s(Items.SNOWBALL), new AspectList().add(Aspect.COLD, 1));
        ThaumcraftApi.registerComplexObjectTag(s(Items.COOKIE), new AspectList().add(Aspect.DESIRE, 1));
        ThaumcraftApi.registerObjectTag(s(Items.POTION), new AspectList().add(Aspect.WATER, 5).add(Aspect.CRYSTAL, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.TORCH), new AspectList().add(Aspect.LIGHT, 5));
        ThaumcraftApi.registerObjectTag(s(Blocks.COBWEB), new AspectList().add(Aspect.TRAP, 5).add(Aspect.BEAST, 1));
        ThaumcraftApi.registerObjectTag(s(Items.FLINT), new AspectList().add(Aspect.EARTH, 5).add(Aspect.TOOL, 5));
        ThaumcraftApi.registerObjectTag("string", new AspectList().add(Aspect.BEAST, 5).add(Aspect.CRAFT, 1));
        ThaumcraftApi.registerObjectTag("slimeball", new AspectList().add(Aspect.WATER, 5).add(Aspect.LIFE, 5).add(Aspect.ALCHEMY, 1));
        ThaumcraftApi.registerObjectTag("leather", new AspectList().add(Aspect.BEAST, 5).add(Aspect.PROTECT, 5));
        ThaumcraftApi.registerObjectTag(s(Items.ROTTEN_FLESH), new AspectList().add(Aspect.MAN, 5).add(Aspect.LIFE, 5).add(Aspect.ENTROPY, 5));
        ThaumcraftApi.registerObjectTag("feather", new AspectList().add(Aspect.FLIGHT, 5).add(Aspect.AIR, 5));
        ThaumcraftApi.registerObjectTag("bone", new AspectList().add(Aspect.DEATH, 5).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag("egg", new AspectList().add(Aspect.LIFE, 5).add(Aspect.BEAST, 5));
        ThaumcraftApi.registerObjectTag(s(Items.SPIDER_EYE), new AspectList().add(Aspect.SENSES, 5).add(Aspect.BEAST, 5).add(Aspect.DEATH, 5));
        ThaumcraftApi.registerObjectTag("gunpowder", new AspectList().add(Aspect.FIRE, 10).add(Aspect.ENTROPY, 10).add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerObjectTag(s(Items.COD), new AspectList().add(Aspect.BEAST, 5).add(Aspect.LIFE, 5).add(Aspect.WATER, 5));
        ThaumcraftApi.registerObjectTag(s(Items.COOKED_COD), new AspectList().add(Aspect.CRAFT, 1).add(Aspect.BEAST, 5).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(s(Items.CHICKEN), new AspectList().add(Aspect.BEAST, 5).add(Aspect.LIFE, 5).add(Aspect.AIR, 5));
        ThaumcraftApi.registerObjectTag(s(Items.COOKED_CHICKEN), new AspectList().add(Aspect.CRAFT, 1).add(Aspect.BEAST, 5).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(s(Items.PORKCHOP), new AspectList().add(Aspect.BEAST, 5).add(Aspect.LIFE, 5).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag(s(Items.COOKED_PORKCHOP), new AspectList().add(Aspect.CRAFT, 1).add(Aspect.BEAST, 5).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(s(Items.BEEF), new AspectList().add(Aspect.BEAST, 5).add(Aspect.LIFE, 5).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag(s(Items.COOKED_BEEF), new AspectList().add(Aspect.CRAFT, 1).add(Aspect.BEAST, 5).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(s(Items.MUTTON), new AspectList().add(Aspect.BEAST, 5).add(Aspect.LIFE, 5).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag(s(Items.COOKED_MUTTON), new AspectList().add(Aspect.CRAFT, 1).add(Aspect.BEAST, 5).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(s(Items.RABBIT), new AspectList().add(Aspect.BEAST, 5).add(Aspect.LIFE, 5).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag(s(Items.COOKED_RABBIT), new AspectList().add(Aspect.CRAFT, 1).add(Aspect.BEAST, 5).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(s(Items.RABBIT_HIDE), new AspectList().add(Aspect.BEAST, 5).add(Aspect.PROTECT, 2));
        ThaumcraftApi.registerObjectTag(s(Items.RABBIT_FOOT), new AspectList().add(Aspect.BEAST, 5).add(Aspect.PROTECT, 5).add(Aspect.MOTION, 10).add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerObjectTag(s(Items.BLAZE_ROD), new AspectList().add(Aspect.FIRE, 15).add(Aspect.ENERGY, 5));
        ThaumcraftApi.registerObjectTag(s(Items.SADDLE), new AspectList().add(Aspect.BEAST, 10).add(Aspect.MOTION, 10).add(Aspect.ORDER, 5));
        ThaumcraftApi.registerObjectTag("enderpearl", new AspectList().add(Aspect.ELDRITCH, 10).add(Aspect.MOTION, 15));
        ThaumcraftApi.registerObjectTag(s(Items.GHAST_TEAR), new AspectList().add(Aspect.UNDEAD, 5).add(Aspect.SOUL, 10).add(Aspect.ALCHEMY, 10));
        ThaumcraftApi.registerObjectTag(s(Items.SKELETON_SKULL), new AspectList().add(Aspect.DEATH, 10).add(Aspect.SOUL, 10).add(Aspect.UNDEAD, 10));
        ThaumcraftApi.registerObjectTag(s(Items.WITHER_SKELETON_SKULL), new AspectList().add(Aspect.DEATH, 10).add(Aspect.SOUL, 10).add(Aspect.UNDEAD, 10));
        ThaumcraftApi.registerObjectTag(s(Items.ZOMBIE_HEAD), new AspectList().add(Aspect.DEATH, 10).add(Aspect.SOUL, 10).add(Aspect.MAN, 10));
        ThaumcraftApi.registerObjectTag(s(Items.PLAYER_HEAD), new AspectList().add(Aspect.DEATH, 10).add(Aspect.SOUL, 10).add(Aspect.MAN, 10));
        ThaumcraftApi.registerObjectTag(s(Items.CREEPER_HEAD), new AspectList().add(Aspect.DEATH, 10).add(Aspect.SOUL, 10).add(Aspect.ENTROPY, 5).add(Aspect.FIRE, 5));
        ThaumcraftApi.registerObjectTag(s(Items.DRAGON_HEAD), new AspectList().add(Aspect.DEATH, 10).add(Aspect.SOUL, 10).add(Aspect.FIRE, 10).add(Aspect.DARKNESS, 10));
        ThaumcraftApi.registerObjectTag(s(Items.DRAGON_BREATH), new AspectList().add(Aspect.DARKNESS, 10).add(Aspect.ENTROPY, 10).add(Aspect.FIRE, 10).add(Aspect.ALCHEMY, 10));
        ThaumcraftApi.registerComplexObjectTag(s(Items.CAULDRON), new AspectList().add(Aspect.ALCHEMY, 15));
        ThaumcraftApi.registerComplexObjectTag(s(Items.FERMENTED_SPIDER_EYE), new AspectList().add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.BLAZE_POWDER), new AspectList().add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.GLISTERING_MELON_SLICE), new AspectList().add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.MAGMA_CREAM), new AspectList().add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerObjectTag(s(Items.TOTEM_OF_UNDYING), new AspectList().add(Aspect.ORDER, 10).add(Aspect.ENTROPY, 10).add(Aspect.LIFE, 25).add(Aspect.UNDEAD, 10));
        ThaumcraftApi.registerObjectTag(s(Items.SHULKER_SHELL), new AspectList().add(Aspect.PROTECT, 10).add(Aspect.ELDRITCH, 5).add(Aspect.BEAST, 5).add(Aspect.VOID, 5));
        ThaumcraftApi.registerObjectTag(s(Blocks.BLACK_SHULKER_BOX), new AspectList(s(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(s(Blocks.BLUE_SHULKER_BOX), new AspectList(s(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(s(Blocks.GREEN_SHULKER_BOX), new AspectList(s(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(s(Blocks.RED_SHULKER_BOX), new AspectList(s(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(s(Blocks.YELLOW_SHULKER_BOX), new AspectList(s(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(s(Blocks.LIGHT_GRAY_SHULKER_BOX), new AspectList(s(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(s(Blocks.WHITE_SHULKER_BOX), new AspectList(s(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(s(Blocks.ORANGE_SHULKER_BOX), new AspectList(s(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(s(Blocks.PINK_SHULKER_BOX), new AspectList(s(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(s(Blocks.GRAY_SHULKER_BOX), new AspectList(s(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(s(Blocks.CYAN_SHULKER_BOX), new AspectList(s(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(s(Blocks.LIGHT_BLUE_SHULKER_BOX), new AspectList(s(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(s(Blocks.LIME_SHULKER_BOX), new AspectList(s(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(s(Blocks.MAGENTA_SHULKER_BOX), new AspectList(s(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(s(Blocks.BROWN_SHULKER_BOX), new AspectList(s(Blocks.PURPLE_SHULKER_BOX)));
        ThaumcraftApi.registerObjectTag(s(Items.MUSIC_DISC_11), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.DESIRE, 15));
        ThaumcraftApi.registerObjectTag(s(Items.MUSIC_DISC_13), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.WATER, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(s(Items.MUSIC_DISC_CAT), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.BEAST, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(s(Items.MUSIC_DISC_CHIRP), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.EARTH, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(s(Items.MUSIC_DISC_FAR), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.ELDRITCH, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(s(Items.MUSIC_DISC_MALL), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.MAN, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(s(Items.MUSIC_DISC_MELLOHI), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.CRAFT, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(s(Items.MUSIC_DISC_STAL), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.DARKNESS, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(s(Items.MUSIC_DISC_STRAD), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.ENERGY, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(s(Items.MUSIC_DISC_WARD), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.LIFE, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(s(Items.MUSIC_DISC_BLOCKS), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.TOOL, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(s(Items.MUSIC_DISC_WAIT), new AspectList().add(Aspect.SENSES, 15).add(Aspect.AIR, 5).add(Aspect.TRAP, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag("netherStar", new AspectList().add(Aspect.ELDRITCH, 10).add(Aspect.MAGIC, 20).add(Aspect.ORDER, 20).add(Aspect.AURA, 10));
        ThaumcraftApi.registerObjectTag(s(Items.CHAINMAIL_HELMET), new AspectList().add(Aspect.METAL, 42));
        ThaumcraftApi.registerObjectTag(s(Items.CHAINMAIL_CHESTPLATE), new AspectList().add(Aspect.METAL, 67));
        ThaumcraftApi.registerObjectTag(s(Items.CHAINMAIL_LEGGINGS), new AspectList().add(Aspect.METAL, 58));
        ThaumcraftApi.registerObjectTag(s(Items.CHAINMAIL_BOOTS), new AspectList().add(Aspect.METAL, 33));
        ThaumcraftApi.registerComplexObjectTag(s(Items.PAPER), new AspectList().add(Aspect.MIND, 2));
        ThaumcraftApi.registerComplexObjectTag(s(Items.ENCHANTED_BOOK), new AspectList(s(Items.BOOK)));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.BOOKSHELF), new AspectList().add(Aspect.MIND, 8));
        ThaumcraftApi.registerObjectTag(s(Blocks.DRAGON_EGG), new AspectList().add(Aspect.ELDRITCH, 15).add(Aspect.BEAST, 15).add(Aspect.DARKNESS, 15).add(Aspect.MOTION, 15).add(Aspect.MAGIC, 5));
        ThaumcraftApi.registerObjectTag(s(Blocks.NETHER_PORTAL), new AspectList().add(Aspect.FIRE, 10).add(Aspect.MOTION, 20).add(Aspect.MAGIC, 10));
        ThaumcraftApi.registerObjectTag(s(Blocks.END_PORTAL), new AspectList().add(Aspect.ELDRITCH, 10).add(Aspect.MOTION, 20).add(Aspect.MAGIC, 10));
        ThaumcraftApi.registerObjectTag(s(Blocks.END_PORTAL_FRAME), new AspectList().add(Aspect.ELDRITCH, 10).add(Aspect.ENERGY, 10).add(Aspect.MOTION, 10).add(Aspect.MAGIC, 5));
        ThaumcraftApi.registerObjectTag(s(Blocks.SPAWNER), new AspectList().add(Aspect.BEAST, 20).add(Aspect.MOTION, 20).add(Aspect.UNDEAD, 20).add(Aspect.MAGIC, 20));
        ThaumcraftApi.registerObjectTag(s(Items.PRISMARINE_SHARD), new AspectList().add(Aspect.WATER, 5).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag(s(Items.PRISMARINE_CRYSTALS), new AspectList().add(Aspect.WATER, 5).add(Aspect.CRYSTAL, 5).add(Aspect.LIGHT, 5));
        ThaumcraftApi.registerObjectTag(s(Items.ELYTRA), new AspectList().add(Aspect.FLIGHT, 20).add(Aspect.MOTION, 15));
        ThaumcraftApi.registerObjectTag(s(Blocks.END_ROD), new AspectList().add(Aspect.FIRE, 1).add(Aspect.LIGHT, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.CHEST), new AspectList().add(Aspect.VOID, 15));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.TRAPPED_CHEST), new AspectList().add(Aspect.TRAP, 10));
        ThaumcraftApi.registerComplexObjectTag(s(Items.ENDER_EYE), new AspectList().add(Aspect.SENSES, 10).add(Aspect.MAGIC, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.ARROW), new AspectList().add(Aspect.AVERSION, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.GLASS_BOTTLE), new AspectList().add(Aspect.VOID, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.GOLDEN_APPLE), new AspectList().add(Aspect.MAGIC, 5).add(Aspect.LIFE, 10));
        ThaumcraftApi.registerComplexObjectTag(s(Items.GOLDEN_APPLE), new AspectList().add(Aspect.MAGIC, 5).add(Aspect.LIFE, 15).add(Aspect.PROTECT, 15));
        ThaumcraftApi.registerComplexObjectTag(s(Items.BOWL), new AspectList().add(Aspect.VOID, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.MUSHROOM_STEW), new AspectList().add(Aspect.LIFE, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.MINECART), new AspectList().add(Aspect.MOTION, 15));
        ThaumcraftApi.registerComplexObjectTag(s(Items.IRON_DOOR), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.ACACIA_DOOR), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.DARK_OAK_DOOR), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.JUNGLE_DOOR), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.OAK_DOOR), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.SPRUCE_DOOR), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.BIRCH_DOOR), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.OAK_BOAT), new AspectList().add(Aspect.WATER, 10).add(Aspect.MOTION, 15));
        ThaumcraftApi.registerComplexObjectTag(s(Items.ACACIA_BOAT), new AspectList().add(Aspect.WATER, 10).add(Aspect.MOTION, 15));
        ThaumcraftApi.registerComplexObjectTag(s(Items.BIRCH_BOAT), new AspectList().add(Aspect.WATER, 10).add(Aspect.MOTION, 15));
        ThaumcraftApi.registerComplexObjectTag(s(Items.DARK_OAK_BOAT), new AspectList().add(Aspect.WATER, 10).add(Aspect.MOTION, 15));
        ThaumcraftApi.registerComplexObjectTag(s(Items.JUNGLE_BOAT), new AspectList().add(Aspect.WATER, 10).add(Aspect.MOTION, 15));
        ThaumcraftApi.registerComplexObjectTag(s(Items.SPRUCE_BOAT), new AspectList().add(Aspect.WATER, 10).add(Aspect.MOTION, 15));
        ThaumcraftApi.registerComplexObjectTag(s(Items.FLINT_AND_STEEL), new AspectList().add(Aspect.FIRE, 10).add(Aspect.TOOL, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.FISHING_ROD), new AspectList().add(Aspect.WATER, 10).add(Aspect.TOOL, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.SHIELD), new AspectList().add(Aspect.PROTECT, 20));
        for (int a = 0; a < 16; ++a) {
            ItemStack sis = s(Items.SHIELD);
            CompoundTag nbttagcompound = new CompoundTag();
            nbttagcompound.putInt("Base", a);
            // Shield base color tag stored in NBT — aspect applies generically for now
            ThaumcraftApi.registerComplexObjectTag(sis, new AspectList().merge(Aspect.PROTECT, 20));
        }
        ThaumcraftApi.registerComplexObjectTag(s(Items.SPECTRAL_ARROW), new AspectList().add(Aspect.SENSES, 10).add(Aspect.MAGIC, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.BUCKET), new AspectList().add(Aspect.VOID, 5));
        ThaumcraftApi.registerObjectTag(s(Items.WATER_BUCKET), new AspectList(s(Items.BUCKET)).add(Aspect.WATER, 20));
        ThaumcraftApi.registerObjectTag(s(Items.LAVA_BUCKET), new AspectList(s(Items.BUCKET)).add(Aspect.FIRE, 15).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag(s(Items.MILK_BUCKET), new AspectList(s(Items.BUCKET)).add(Aspect.LIFE, 10).add(Aspect.BEAST, 5).add(Aspect.WATER, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.BREWING_STAND), new AspectList().add(Aspect.CRAFT, 15).add(Aspect.ALCHEMY, 25));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.STONE_BUTTON), new AspectList().add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.RAIL), new AspectList().add(Aspect.MOTION, 10));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.DETECTOR_RAIL), new AspectList().add(Aspect.MECHANISM, 5).add(Aspect.SENSES, 1));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.POWERED_RAIL), new AspectList().add(Aspect.MECHANISM, 5).add(Aspect.ENERGY, 1));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.ACTIVATOR_RAIL), new AspectList().add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.ACACIA_FENCE_GATE), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.DARK_OAK_FENCE_GATE), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.JUNGLE_FENCE_GATE), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.DARK_OAK_FENCE_GATE), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.SPRUCE_FENCE_GATE), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.BIRCH_FENCE_GATE), new AspectList().add(Aspect.TRAP, 5).add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.OAK_PRESSURE_PLATE), new AspectList().add(Aspect.MECHANISM, 5).add(Aspect.SENSES, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.STONE_PRESSURE_PLATE), new AspectList().add(Aspect.MECHANISM, 5).add(Aspect.SENSES, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.LIGHT_WEIGHTED_PRESSURE_PLATE), new AspectList().add(Aspect.MECHANISM, 5).add(Aspect.SENSES, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.HEAVY_WEIGHTED_PRESSURE_PLATE), new AspectList().add(Aspect.MECHANISM, 5).add(Aspect.SENSES, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.LEVER), new AspectList().add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.PISTON), new AspectList().add(Aspect.MECHANISM, 10).add(Aspect.MOTION, 10));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.STICKY_PISTON), new AspectList().add(Aspect.MECHANISM, 10).add(Aspect.MOTION, 10));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.JUKEBOX), new AspectList().add(Aspect.SENSES, 20).add(Aspect.MECHANISM, 10).add(Aspect.AIR, 15));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.NOTE_BLOCK), new AspectList().add(Aspect.SENSES, 20).add(Aspect.MECHANISM, 10).add(Aspect.AIR, 15));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.OAK_TRAPDOOR), new AspectList().add(Aspect.MOTION, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.FURNACE), new AspectList().add(Aspect.FIRE, 10));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.ENCHANTING_TABLE), new AspectList().add(Aspect.MAGIC, 25).add(Aspect.CRAFT, 15));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.CRAFTING_TABLE), new AspectList().add(Aspect.CRAFT, 20));
        ThaumcraftApi.registerComplexObjectTag(s(Items.CLOCK), new AspectList().add(Aspect.MECHANISM, 10));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.BEACON), new AspectList().add(Aspect.AURA, 10).add(Aspect.MAGIC, 10).add(Aspect.EXCHANGE, 10));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.OAK_BUTTON), new AspectList().add(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.CARROT_ON_A_STICK), new AspectList().add(Aspect.MOTION, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerComplexObjectTag(s(Items.FLOWER_POT), new AspectList().add(Aspect.VOID, 5).add(Aspect.PLANT, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.GOLDEN_CARROT), new AspectList().add(Aspect.SENSES, 10).add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.ENDER_CHEST), new AspectList().merge(Aspect.EXCHANGE, 10).merge(Aspect.MOTION, 10).merge(Aspect.VOID, 20));
        ThaumcraftApi.registerComplexObjectTag(s(Items.COMPARATOR), new AspectList().merge(Aspect.MECHANISM, 15).merge(Aspect.ORDER, 5).merge(Aspect.SENSES, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Items.REPEATER), new AspectList().merge(Aspect.MECHANISM, 15).merge(Aspect.ENERGY, 10));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.HOPPER), new AspectList().merge(Aspect.MECHANISM, 5).merge(Aspect.EXCHANGE, 10).merge(Aspect.VOID, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.DROPPER), new AspectList().merge(Aspect.MECHANISM, 5).merge(Aspect.EXCHANGE, 10).merge(Aspect.VOID, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.DISPENSER), new AspectList().merge(Aspect.MECHANISM, 5).merge(Aspect.EXCHANGE, 10).merge(Aspect.VOID, 5));
        ThaumcraftApi.registerObjectTag(s(Blocks.TRIPWIRE_HOOK), new AspectList().add(Aspect.SENSES, 5).add(Aspect.MECHANISM, 5).add(Aspect.TRAP, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.TRIPWIRE), new AspectList().merge(Aspect.SENSES, 5).merge(Aspect.MECHANISM, 5).merge(Aspect.TRAP, 5));
        ThaumcraftApi.registerComplexObjectTag(s(Blocks.DAYLIGHT_DETECTOR), new AspectList().merge(Aspect.SENSES, 10).merge(Aspect.LIGHT, 10).merge(Aspect.MECHANISM, 5));
        ThaumcraftApi.registerComplexObjectTag("gear*", new AspectList().add(Aspect.MECHANISM, 5));
        for (net.minecraft.core.Holder.Reference<net.minecraft.world.item.alchemy.Potion> potionHolder :
                net.minecraft.core.registries.BuiltInRegistries.POTION.listElements().toList()) {
            net.minecraft.world.item.alchemy.PotionContents contents =
                new net.minecraft.world.item.alchemy.PotionContents(
                    java.util.Optional.of(potionHolder),
                    java.util.Optional.empty(),
                    java.util.List.of(),
                    java.util.Optional.empty());
            java.util.function.Function<net.minecraft.world.item.Item, ItemStack> mkStack = item -> {
                ItemStack st = new ItemStack(item);
                st.set(net.minecraft.core.component.DataComponents.POTION_CONTENTS, contents);
                return st;
            };
            ThaumcraftApi.registerObjectTag(mkStack.apply(Items.POTION),
                getPotionAspects(potionHolder).add(Aspect.WATER, 5));
            ThaumcraftApi.registerObjectTag(mkStack.apply(Items.TIPPED_ARROW),
                getPotionAspects(potionHolder).add(Aspect.AVERSION, 5));
            ThaumcraftApi.registerObjectTag(mkStack.apply(Items.SPLASH_POTION),
                getPotionAspects(potionHolder).add(Aspect.ENERGY, 5));
            ThaumcraftApi.registerObjectTag(mkStack.apply(Items.LINGERING_POTION),
                getPotionAspects(potionHolder).add(Aspect.TRAP, 5));
        }
        ThaumcraftApi.registerObjectTag(s(Items.WHITE_DYE), new AspectList().add(Aspect.WATER, 2).add(Aspect.BEAST, 2));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.phial), new AspectList().add(Aspect.VOID, 3));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.phial), new AspectList());
        ThaumcraftApi.registerObjectTag(s(BlocksTC.grassAmbient), new AspectList(s(Blocks.GRASS_BLOCK)).add(Aspect.LIGHT, 5));
        ThaumcraftApi.registerComplexObjectTag(s(BlocksTC.tableWood), new AspectList().add(Aspect.TOOL, 1));
        ThaumcraftApi.registerComplexObjectTag(s(BlocksTC.tableStone), new AspectList().add(Aspect.TOOL, 1));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.arcaneWorkbench), new AspectList(s(Blocks.CRAFTING_TABLE)).add(Aspect.MAGIC, 5).add(Aspect.AURA, 5));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.tripleMeatTreat), new AspectList().add(Aspect.LIFE, 10).add(Aspect.DESIRE, 10));
        // Fluid bucket aspect tags (fluxGoo, liquidDeath) registered with fluid bucket items in TCFluids
        ThaumcraftApi.registerObjectTag("clusterIron", new AspectList().add(Aspect.ORDER, 5).add(Aspect.METAL, 15).add(Aspect.EARTH, 5));
        ThaumcraftApi.registerObjectTag("clusterGold", new AspectList().add(Aspect.ORDER, 5).add(Aspect.METAL, 15).add(Aspect.EARTH, 5).add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag("clusterCinnabar", new AspectList().add(Aspect.ORDER, 5).add(Aspect.METAL, 15).add(Aspect.EARTH, 5).add(Aspect.ALCHEMY, 5).add(Aspect.DEATH, 5));
        ThaumcraftApi.registerObjectTag("clusterQuartz", new AspectList().add(Aspect.ORDER, 5).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag("oreCinnabar", new AspectList().add(Aspect.EARTH, 5).add(Aspect.METAL, 10).add(Aspect.ALCHEMY, 5).add(Aspect.DEATH, 5));
        ThaumcraftApi.registerObjectTag("oreAmber", new AspectList().add(Aspect.EARTH, 5).add(Aspect.TRAP, 10).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag("quicksilver", new AspectList().add(Aspect.METAL, 10).add(Aspect.DEATH, 5).add(Aspect.ALCHEMY, 5));
        ThaumcraftApi.registerObjectTag("gemAmber", new AspectList().add(Aspect.TRAP, 10).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.nuggets), new AspectList().add(Aspect.EARTH, 5).add(Aspect.ORDER, 5).add(Aspect.METAL, 5));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.crystalAir), new AspectList().add(Aspect.AIR, 15).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.crystalFire), new AspectList().add(Aspect.FIRE, 15).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.crystalWater), new AspectList().add(Aspect.WATER, 15).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.crystalEarth), new AspectList().add(Aspect.EARTH, 15).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.crystalOrder), new AspectList().add(Aspect.ORDER, 15).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.crystalEntropy), new AspectList().add(Aspect.ENTROPY, 15).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.crystalTaint), new AspectList().add(Aspect.FLUX, 15).add(Aspect.CRYSTAL, 10));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.taintFibre), new AspectList().add(Aspect.PLANT, 5).add(Aspect.FLUX, 10));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.taintCrust), new AspectList().add(Aspect.LIFE, 5).add(Aspect.FLUX, 5));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.taintSoil), new AspectList().add(Aspect.EARTH, 5).add(Aspect.FLUX, 5));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.taintGeyser), new AspectList().add(Aspect.AURA, 5).add(Aspect.WATER, 5).add(Aspect.FLUX, 10));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.taintRock), new AspectList().add(Aspect.EARTH, 10).add(Aspect.FLUX, 5));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.taintFeature), new AspectList().add(Aspect.AURA, 5).add(Aspect.BEAST, 5).add(Aspect.FLUX, 10));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.taintLog), new AspectList().add(Aspect.PLANT, 5).add(Aspect.FLUX, 5));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.logGreatwood), new AspectList().add(Aspect.PLANT, 20).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.logSilverwood), new AspectList().add(Aspect.PLANT, 20).add(Aspect.AURA, 5));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.leafGreatwood), new AspectList().add(Aspect.PLANT, 5));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.leafSilverwood), new AspectList().add(Aspect.PLANT, 5));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.saplingGreatwood), new AspectList().add(Aspect.PLANT, 15).add(Aspect.LIFE, 5));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.saplingSilverwood), new AspectList().add(Aspect.PLANT, 15).add(Aspect.AURA, 5));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.shimmerleaf), new AspectList().add(Aspect.PLANT, 5).add(Aspect.AURA, 10).add(Aspect.ENERGY, 5));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.cinderpearl), new AspectList().add(Aspect.PLANT, 5).add(Aspect.AURA, 5).add(Aspect.FIRE, 10));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.vishroom), new AspectList().add(Aspect.PLANT, 2).add(Aspect.DEATH, 1).add(Aspect.MAGIC, 1).add(Aspect.ENTROPY, 1));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.stoneAncient), new AspectList().add(Aspect.EARTH, 5).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.stoneAncientTile), new AspectList().add(Aspect.EARTH, 5).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.stoneAncientRock), new AspectList().add(Aspect.EARTH, 5).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.stoneEldritchTile), new AspectList().add(Aspect.EARTH, 5).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.stoneAncientDoorway), new AspectList().add(Aspect.METAL, 5).add(Aspect.ELDRITCH, 5).add(Aspect.TRAP, 5));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.stoneAncientGlyphed), new AspectList().add(Aspect.METAL, 5).add(Aspect.ELDRITCH, 5).add(Aspect.MIND, 5));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.stonePorous), new AspectList().add(Aspect.EARTH, 5).add(Aspect.VOID, 5));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.researchTable), new AspectList(s(BlocksTC.tableWood)).add(Aspect.MIND, 5));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.brain), new AspectList().add(Aspect.LIFE, 5).add(Aspect.MIND, 20).add(Aspect.UNDEAD, 10));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.lootBag), new AspectList().add(Aspect.DESIRE, 10));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.lootBag), new AspectList().add(Aspect.DESIRE, 20));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.lootBag), new AspectList().add(Aspect.DESIRE, 30));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.lootUrnCommon), new AspectList().add(Aspect.DESIRE, 10).add(Aspect.EARTH, 2));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.lootUrnUncommon), new AspectList().add(Aspect.DESIRE, 20).add(Aspect.EARTH, 2));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.lootUrnRare), new AspectList().add(Aspect.DESIRE, 30).add(Aspect.EARTH, 2));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.lootCrateCommon), new AspectList().add(Aspect.DESIRE, 10).add(Aspect.PLANT, 2));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.lootCrateUncommon), new AspectList().add(Aspect.DESIRE, 20).add(Aspect.PLANT, 2));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.lootCrateRare), new AspectList().add(Aspect.DESIRE, 30).add(Aspect.PLANT, 2));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.chunks), new AspectList().add(Aspect.LIFE, 5).add(Aspect.ENTROPY, 1));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.salisMundus), new AspectList().add(Aspect.MAGIC, 5).add(Aspect.ENERGY, 5));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.crucible), new AspectList(s(Items.CAULDRON)).add(Aspect.CRAFT, 20).add(Aspect.ALCHEMY, 20));
        for (Block ca : BlocksTC.candles.values()) {
            ThaumcraftApi.registerComplexObjectTag(s(ca), new AspectList().add(Aspect.LIGHT, 5));
        }
        ThaumcraftApi.registerObjectTag(s(ItemsTC.thaumonomicon), new AspectList(s(Blocks.BOOKSHELF)).merge(Aspect.MAGIC, 10));
        ThaumcraftApi.registerComplexObjectTag(s(BlocksTC.pedestalArcane), new AspectList().add(Aspect.MAGIC, 3).add(Aspect.AIR, 3));
        ThaumcraftApi.registerComplexObjectTag(s(BlocksTC.pedestalAncient), new AspectList().add(Aspect.MAGIC, 3).add(Aspect.ELDRITCH, 3));
        ThaumcraftApi.registerComplexObjectTag(s(BlocksTC.pedestalEldritch), new AspectList().add(Aspect.MAGIC, 3).add(Aspect.ELDRITCH, 3));
        ThaumcraftApi.registerComplexObjectTag(s(ItemsTC.thaumometer), new AspectList().add(Aspect.SENSES, 10).add(Aspect.AURA, 10));
        ThaumcraftApi.registerComplexObjectTag(s(ItemsTC.goggles), new AspectList().merge(Aspect.SENSES, 10).merge(Aspect.AURA, 10));
        ThaumcraftApi.registerComplexObjectTag(s(BlocksTC.arcaneEar), new AspectList().add(Aspect.SENSES, 20));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.amuletVis), new AspectList().add(Aspect.AURA, 20).add(Aspect.METAL, 5).add(Aspect.MAGIC, 5));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.baubles), new AspectList().add(Aspect.AURA, 5).add(Aspect.METAL, 5).add(Aspect.MAGIC, 20));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.crimsonPlateChest), new AspectList(s(Items.IRON_CHESTPLATE)).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.crimsonPraetorChest), new AspectList(s(Items.IRON_CHESTPLATE)).add(Aspect.ELDRITCH, 10));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.crimsonRobeChest), new AspectList(s(Items.LEATHER_CHESTPLATE)).add(Aspect.MAGIC, 5).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.crimsonPlateLegs), new AspectList(s(Items.IRON_LEGGINGS)).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.crimsonPraetorLegs), new AspectList(s(Items.IRON_LEGGINGS)).add(Aspect.ELDRITCH, 10));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.crimsonRobeLegs), new AspectList(s(Items.LEATHER_LEGGINGS)).add(Aspect.MAGIC, 5).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.crimsonPlateHelm), new AspectList(s(Items.IRON_HELMET)).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.crimsonPraetorHelm), new AspectList(s(Items.IRON_HELMET)).add(Aspect.ELDRITCH, 10));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.crimsonRobeHelm), new AspectList(s(Items.LEATHER_HELMET)).add(Aspect.MAGIC, 5).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.crimsonBoots), new AspectList(s(Items.IRON_BOOTS)).add(Aspect.ELDRITCH, 5));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.crimsonBlade), new AspectList(s(Items.IRON_SWORD)).add(Aspect.ELDRITCH, 10).add(Aspect.DEATH, 10));
        for (Block ca : BlocksTC.banners.values()) {
            ThaumcraftApi.registerComplexObjectTag(s(ca), new AspectList().add(Aspect.ELDRITCH, 5));
        }
        ThaumcraftApi.registerObjectTag(s(ItemsTC.eldritchEye), new AspectList().add(Aspect.ELDRITCH, 15).add(Aspect.AURA, 15).add(Aspect.SENSES, 15).add(Aspect.SOUL, 15));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.curio), new AspectList().add(Aspect.MIND, 15).add(Aspect.MAGIC, 15));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.curio), new AspectList().add(Aspect.MIND, 15).add(Aspect.BEAST, 15));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.curio), new AspectList().add(Aspect.MIND, 15).add(Aspect.DEATH, 15));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.curio), new AspectList().add(Aspect.MIND, 15).add(Aspect.ELDRITCH, 15));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.curio), new AspectList().add(Aspect.MIND, 30));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.curio), new AspectList().add(Aspect.MIND, 15).add(Aspect.FLUX, 15));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.curio), new AspectList().add(Aspect.MIND, 15).add(Aspect.ELDRITCH, 5).add(Aspect.SOUL, 5).add(Aspect.MAGIC, 5));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.runedTablet), new AspectList().add(Aspect.TRAP, 15).add(Aspect.MIND, 15).add(Aspect.MECHANISM, 15));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.celestialNotes), new AspectList().add(Aspect.MIND, 5).add(Aspect.DARKNESS, 5).add(Aspect.LIGHT, 5));
        ThaumcraftApi.registerObjectTag(s(ItemsTC.primordialPearl), new AspectList().add(Aspect.AIR, 10).add(Aspect.FIRE, 10).add(Aspect.WATER, 10).add(Aspect.EARTH, 10).add(Aspect.ORDER, 10).add(Aspect.ENTROPY, 10));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.eldritch), new AspectList().add(Aspect.VOID, 10).add(Aspect.ELDRITCH, 10));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.eldritch), new AspectList().add(Aspect.VOID, 10).add(Aspect.ELDRITCH, 10));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.eldritch), new AspectList().add(Aspect.VOID, 10).add(Aspect.ELDRITCH, 10));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.eldritch), new AspectList().add(Aspect.VOID, 10).add(Aspect.ELDRITCH, 10));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.eldritch), new AspectList().add(Aspect.VOID, 10).add(Aspect.ELDRITCH, 10).add(Aspect.MECHANISM, 10));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.eldritch), new AspectList().add(Aspect.VOID, 10).add(Aspect.ELDRITCH, 10));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.eldritch), new AspectList().add(Aspect.VOID, 10).add(Aspect.ELDRITCH, 10).add(Aspect.MOTION, 15));
        ThaumcraftApi.registerObjectTag(s(BlocksTC.eldritch), new AspectList().add(Aspect.VOID, 10).add(Aspect.ELDRITCH, 10).add(Aspect.BEAST, 15));
    }
    
    public static AspectList getPotionAspects(net.minecraft.core.Holder<net.minecraft.world.item.alchemy.Potion> potionHolder) {
        AspectList tmp = new AspectList();
        java.util.List<net.minecraft.world.effect.MobEffectInstance> effects = potionHolder.value().getEffects();
        if (effects.isEmpty()) return tmp.add(Aspect.WATER, 5);
        for (net.minecraft.world.effect.MobEffectInstance effect : effects) {
            AspectList ea = getEffectAspects(effect);
            for (Aspect a : ea.getAspects()) tmp.add(a, ea.getAmount(a));
            tmp.add(Aspect.ALCHEMY, 3);
        }
        for (Aspect a : tmp.getAspects()) tmp.remove(a, (int)(tmp.getAmount(a) * 0.66));
        return tmp.size() == 0 ? new AspectList().add(Aspect.MAGIC, 5).add(Aspect.ALCHEMY, 5) : tmp;
    }

    private static AspectList getEffectAspects(net.minecraft.world.effect.MobEffectInstance effect) {
        net.minecraft.world.effect.MobEffect type = effect.getEffect().value();
        if (type == net.minecraft.world.effect.MobEffects.SPEED.value())    return new AspectList().add(Aspect.MOTION, 5);
        if (type == net.minecraft.world.effect.MobEffects.SLOWNESS.value()) return new AspectList().add(Aspect.MOTION, 5).add(Aspect.ENTROPY, 5);
        if (type == net.minecraft.world.effect.MobEffects.HASTE.value())         return new AspectList().add(Aspect.TOOL, 5).add(Aspect.MOTION, 5);
        if (type == net.minecraft.world.effect.MobEffects.MINING_FATIGUE.value())      return new AspectList().add(Aspect.TOOL, 5).add(Aspect.ENTROPY, 5);
        if (type == net.minecraft.world.effect.MobEffects.STRENGTH.value())      return new AspectList().add(Aspect.AVERSION, 5);
        if (type == net.minecraft.world.effect.MobEffects.INSTANT_HEALTH.value())              return new AspectList().add(Aspect.LIFE, 5);
        if (type == net.minecraft.world.effect.MobEffects.INSTANT_DAMAGE.value())              return new AspectList().add(Aspect.DEATH, 5);
        if (type == net.minecraft.world.effect.MobEffects.JUMP_BOOST.value())              return new AspectList().add(Aspect.MOTION, 5).add(Aspect.AIR, 5);
        if (type == net.minecraft.world.effect.MobEffects.NAUSEA.value())         return new AspectList().add(Aspect.MIND, 5).add(Aspect.ENTROPY, 5);
        if (type == net.minecraft.world.effect.MobEffects.REGENERATION.value())      return new AspectList().add(Aspect.LIFE, 5).add(Aspect.ALCHEMY, 5);
        if (type == net.minecraft.world.effect.MobEffects.RESISTANCE.value()) return new AspectList().add(Aspect.PROTECT, 5);
        if (type == net.minecraft.world.effect.MobEffects.FIRE_RESISTANCE.value())   return new AspectList().add(Aspect.FIRE, 5).add(Aspect.PROTECT, 5);
        if (type == net.minecraft.world.effect.MobEffects.WATER_BREATHING.value())   return new AspectList().add(Aspect.WATER, 5).add(Aspect.AIR, 5);
        if (type == net.minecraft.world.effect.MobEffects.INVISIBILITY.value())      return new AspectList().add(Aspect.DARKNESS, 5);
        if (type == net.minecraft.world.effect.MobEffects.BLINDNESS.value())         return new AspectList().add(Aspect.SENSES, 5).add(Aspect.DARKNESS, 5);
        if (type == net.minecraft.world.effect.MobEffects.NIGHT_VISION.value())      return new AspectList().add(Aspect.SENSES, 5).add(Aspect.LIGHT, 5);
        if (type == net.minecraft.world.effect.MobEffects.HUNGER.value())            return new AspectList().add(Aspect.MAN, 5).add(Aspect.DESIRE, 5);
        if (type == net.minecraft.world.effect.MobEffects.WEAKNESS.value())          return new AspectList().add(Aspect.AVERSION, 5).add(Aspect.ENTROPY, 5);
        if (type == net.minecraft.world.effect.MobEffects.POISON.value())            return new AspectList().add(Aspect.DEATH, 5).add(Aspect.ALCHEMY, 5);
        if (type == net.minecraft.world.effect.MobEffects.WITHER.value())            return new AspectList().add(Aspect.DEATH, 5).add(Aspect.UNDEAD, 5);
        if (type == net.minecraft.world.effect.MobEffects.HEALTH_BOOST.value())      return new AspectList().add(Aspect.LIFE, 5).add(Aspect.PROTECT, 5);
        if (type == net.minecraft.world.effect.MobEffects.ABSORPTION.value())        return new AspectList().add(Aspect.PROTECT, 5).add(Aspect.LIFE, 5);
        if (type == net.minecraft.world.effect.MobEffects.SATURATION.value())        return new AspectList().add(Aspect.MAN, 5).add(Aspect.LIFE, 5);
        if (type == net.minecraft.world.effect.MobEffects.LEVITATION.value())        return new AspectList().add(Aspect.MOTION, 5).add(Aspect.AIR, 5);
        if (type == net.minecraft.world.effect.MobEffects.SLOW_FALLING.value())      return new AspectList().add(Aspect.MOTION, 3).add(Aspect.AIR, 5);
        if (type == net.minecraft.world.effect.MobEffects.LUCK.value())              return new AspectList().add(Aspect.DESIRE, 5);
        if (type == net.minecraft.world.effect.MobEffects.UNLUCK.value())            return new AspectList().add(Aspect.DESIRE, 5).add(Aspect.ENTROPY, 5);
        return new AspectList().add(Aspect.MAGIC, 3).add(Aspect.ALCHEMY, 3);
    }
    
    static {
        ConfigAspects.dyes = new String[] { "dyeBlack", "dyeRed", "dyeGreen", "dyeBrown", "dyeBlue", "dyePurple", "dyeCyan", "dyeLightGray", "dyeGray", "dyePink", "dyeLime", "dyeYellow", "dyeLightBlue", "dyeMagenta", "dyeOrange", "dyeWhite" };
    }
}
